CRYPT     = ActiveSupport::MessageEncryptor.new(Rails.application.secrets.secret_key_base)

  BALLBYBALL_SEO_JSON            = 'ballbyball.json'
  SEO_PAGE_TITLE_TAG             = 'title'
  SEO_PAGE_META_DESCRIPTION      = 'meta_description'
  SEO_PAGE_META_KEYWORDS         = 'meta_keywords'
  SEO_PAGE_HEADER_TAG            = 'header_title'
  SEO_PAGE_INTRO_TAG             = 'intro'
  SEO_PAGE_SECTION2_TAG          = 'section2'
  SEO_PAGE_SECTION3_TAG          = 'section3'
  SEO_PAGE_END_PARA_TAG          = 'end_para'
  SEO_PAGE_TITLE                 = 'CricketLive'
  TEAM_FLAGS_PATH                = '/assets/team_flags/'
  DEFAULT_TEAM_FLAGS_PATH        = '/assets/team_flags/Wicket.png'
  PLAYER_URL                     = 'http://cdn.cricapi.com/players/'
  NO_PLAYER_URL                  = '/assets/no_player.png'
